# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-11 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxfFoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=16)),
                ('typename', models.CharField(max_length=32)),
                ('childtypenames', models.CharField(max_length=128)),
                ('typesort', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'axf_foodtype',
            },
        ),
        migrations.CreateModel(
            name='AxfGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=16)),
                ('productimg', models.CharField(max_length=64)),
                ('productname', models.CharField(max_length=128)),
                ('productlongname', models.CharField(max_length=32)),
                ('isxf', models.CharField(max_length=16)),
                ('pmdesc', models.CharField(max_length=16)),
                ('specifics', models.CharField(max_length=16)),
                ('price', models.FloatField()),
                ('marketprice', models.FloatField()),
                ('categoryid', models.CharField(max_length=16)),
                ('childcid', models.CharField(max_length=16)),
                ('childcidname', models.CharField(max_length=32)),
                ('dealerid', models.CharField(max_length=16)),
                ('storenums', models.CharField(max_length=16)),
                ('productnum', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
